import { BlogPost } from './types';
import { Routes } from '@/content/routes';

const blogPosts: BlogPost[] = [
  {
    title: 'Dive into the World of Bridgerton: Palettes Inspired by Iconic Families and Characters',
    subtitle: 'Discover color palettes inspired by the families and characters of Bridgerton. Bring a touch of Regency-era elegance and drama to your designs with these rich and diverse color schemes.',
    minutesToRead: 5,
    createdAt: '2025-08-15',
    url: Routes.ExploringColorsOfBridgertonBlog,
    tags: ['Bridgerton', 'Colors', 'Design Inspiration', 'Web Design'],
    thumbnail: '/blog-images/exploring-colors-of-bridgerton-1.jpeg',
    toolKey: 'blog-exploring-colors-of-bridgerton',
  },
  {
    title: 'QR Codes in Modern Web & Design',
    subtitle: 'Discover how QR codes are revolutionizing modern web design and marketing, offering innovative ways to enhance user engagement and bridge physical-digital experiences.',
    minutesToRead: 4,
    createdAt: '2025-07-10',
    url: Routes.QRCodesInModernWebDesignBlog,
    tags: ['QR Codes', 'Web Design', 'Digital Marketing', 'Mobile Integration'],
    thumbnail: '/blog-images/qr-codes-in-modern-web-design-1.jpeg',
    toolKey: 'blog-qr-codes-in-modern-web-design',
  },
  {
    title: 'Accessible Web Design: Ensuring Everyone Can See Your Work',
    subtitle: 'Learn the essential principles of accessible web design to create inclusive websites that can be enjoyed by everyone, regardless of their abilities or devices.',
    minutesToRead: 5,
    createdAt: '2025-07-05',
    url: Routes.AccessibleWebDesignBlog,
    tags: ['Web Accessibility', 'Inclusive Design', 'User Experience', 'WCAG'],
    thumbnail: '/blog-images/accessible-web-design-ensuring-everyone-can-see-your-work-1.jpeg',
    toolKey: 'blog-accessible-web-design',
  },
  {
    title: 'The Psychology of Color in Web Design',
    subtitle: 'Explore how different colors influence user behavior and emotions, and learn how to choose the right colors to create engaging and effective web designs.',
    minutesToRead: 4,
    createdAt: '2025-06-03',
    url: Routes.PsychologyOfColorBlog,
    tags: ['Colors', 'User Experience', 'Web Design'],
    thumbnail: '/blog-images/the-psychology-of-color-in-web-design-1.jpeg',
    toolKey: 'blog-psychology-of-color',
  },
  {
    title: 'Creating Color Steps for Heatmaps',
    subtitle: 'Learn how to use stepped gradients to create clear and informative heatmaps, enhancing your data visualizations with distinct color bands.',
    minutesToRead: 3,
    createdAt: '2025-05-30',
    url: Routes.ColorStepsForHeatmapsBlog,
    tags: ['Data Visualization', 'Colors', 'Design Techniques'],
    thumbnail: '/blog-images/creating-color-steps-for-heatmaps-1.jpeg',
    toolKey: 'blog-creating-color-steps-for-heatmaps',
  },
  {
    title: 'Color Theory for Digital Design: Basics and Beyond',
    subtitle: 'Explore the fundamentals of color theory and learn how to apply these principles in digital design to create visually appealing and effective projects.',
    minutesToRead: 4,
    createdAt: '2025-05-27',
    url: Routes.ColorTheoryForDigitalDesignBlog,
    tags: ['Colors', 'Design Principles', 'Digital Design'],
    thumbnail: '/blog-images/color-theory-for-digital-design-1.jpeg',
    toolKey: 'blog-color-theory-for-digital-design',
  },
  {
    title: 'Integrating Base64 Images in Your Web Projects',
    subtitle: 'Discover how to use Base64 encoding to embed images directly in your HTML and CSS, reduce HTTP requests, and streamline your web projects.',
    minutesToRead: 4,
    createdAt: '2025-05-18',
    url: Routes.Base64ImagesBlog,
    tags: ['Images', 'Web Development', 'Optimization'],
    thumbnail: '/blog-images/integrating-base64-images-in-your-web-projects-1.jpeg',
    toolKey: 'blog-integrating-base64-images-in-your-web-projects',
  },
  {
    title: 'Essential Tools for Designers in 2025',
    subtitle: 'Equip yourself with the must-have tools for designers in 2025, from comprehensive design software to collaborative platforms and graphic resources.',
    minutesToRead: 5,
    createdAt: '2025-05-11',
    url: Routes.ToolsForDesignersBlog,
    tags: ['Tools', 'Design Resources', 'Productivity'],
    thumbnail: '/blog-images/essential-tools-for-designers-in-2025-1.jpeg',
    toolKey: 'blog-essential-tools-for-designers-in-2025',
  },
  {
    title: 'Blending Colors for Unique Palettes',
    subtitle: 'Master the art of blending colors to create harmonious and unique palettes for web design, branding, and digital art projects.',
    minutesToRead: 3,
    createdAt: '2025-05-07',
    url: Routes.BlendingColorsBlog,
    tags: ['Colors', 'Design Techniques', 'Digital Design'],
    thumbnail: '/blog-images/blending-colors-for-unique-palettes-1.jpeg',
    toolKey: 'blog-blending-colors-for-unique-palettes',
  },
  {
    title: 'Optimizing Images for the Web: Formats and Quality',
    subtitle: 'Find out how to optimize images for faster loading times and better web performance by selecting the right formats and adjusting quality settings.',
    minutesToRead: 4,
    createdAt: '2025-04-28',
    url: Routes.OptimizingImagesBlog,
    tags: ['Images', 'Optimization', 'Web Performance'],
    thumbnail: '/blog-images/optimizing-images-for-the-web-1.jpeg',
    toolKey: 'blog-optimizing-images-for-the-web',
  },
  {
    title: 'Top Trends in Web Design for 2025',
    subtitle: 'Stay ahead with the latest web design trends for 2025, from bold typography and dark mode to immersive 3D visuals and AI integration.',
    minutesToRead: 5,
    createdAt: '2025-04-20',
    url: Routes.WebDesignTrendsBlog,
    tags: ['Trends', 'Web Design', 'Innovation'],
    thumbnail: '/blog-images/top-trends-in-web-design-for-2025-1.jpeg',
    toolKey: 'blog-top-trends-in-web-design-for-2025',
  },
  {
    title: 'Understanding Color Formats: From Hex to CMYK',
    subtitle: 'Learn about the different color formats used in digital design, including HEX, RGB, HSL, and CMYK, and how to convert and apply them effectively.',
    minutesToRead: 4,
    createdAt: '2025-04-15',
    url: Routes.UnderstandingColorFormatsBlog,
    tags: ['Colors', 'Digital Design', 'Technical'],
    thumbnail: '/blog-images/understanding-color-formats-1.jpeg',
    toolKey: 'blog-understanding-color-formats',
  }
];

export { blogPosts };