const emojiEntities = [
  {
    groupName: 'Smileys & People',
    characters: [
      { emoji: '😀', code: '&#128512;', description: 'Grinning Face' },
      { emoji: '😃', code: '&#128515;', description: 'Grinning Face with Big Eyes' },
      { emoji: '😁', code: '&#128513;', description: 'Beaming Face with Smiling Eyes' },
      { emoji: '😂', code: '&#128514;', description: 'Face with Tears of Joy' },
      { emoji: '😊', code: '&#128522;', description: 'Smiling Face with Smiling Eyes' },
      { emoji: '😍', code: '&#128525;', description: 'Smiling Face with Heart-Eyes' },
      { emoji: '😎', code: '&#128526;', description: 'Smiling Face with Sunglasses' },
      { emoji: '🤔', code: '&#129300;', description: 'Thinking Face' },
      { emoji: '😏', code: '&#128527;', description: 'Smirking Face' },
      { emoji: '😢', code: '&#128546;', description: 'Crying Face' },
      { emoji: '😭', code: '&#128557;', description: 'Loudly Crying Face' },
      { emoji: '😡', code: '&#128545;', description: 'Pouting Face' },
      { emoji: '🤯', code: '&#129327;', description: 'Exploding Head' },
      { emoji: '🤗', code: '&#129303;', description: 'Hugging Face' },
      { emoji: '😇', code: '&#128519;', description: 'Smiling Face with Halo' },
      { emoji: '🤩', code: '&#129321;', description: 'Star-Struck' },
      { emoji: '😜', code: '&#128540;', description: 'Winking Face with Tongue' },
      { emoji: '🤪', code: '&#129322;', description: 'Zany Face' },
      { emoji: '🤫', code: '&#129323;', description: 'Shushing Face' },
      { emoji: '🤭', code: '&#129325;', description: 'Face with Hand Over Mouth' },
      { emoji: '🙃', code: '&#128579;', description: 'Upside-Down Face' },
      { emoji: '😤', code: '&#128548;', description: 'Face with Steam From Nose' },
      { emoji: '😥', code: '&#128549;', description: 'Sad but Relieved Face' },
      { emoji: '😴', code: '&#128564;', description: 'Sleeping Face' },
      { emoji: '😌', code: '&#128524;', description: 'Relieved Face' },
      { emoji: '🤤', code: '&#129316;', description: 'Drooling Face' },
      { emoji: '😷', code: '&#128567;', description: 'Face with Medical Mask' },
      { emoji: '🤷', code: '&#129335;', description: 'Person Shrugging' },
      { emoji: '🤷‍♂️', code: '&#129335;&#9794;', description: 'Man Shrugging' },
      { emoji: '🤷‍♀️', code: '&#129335;&#9792;', description: 'Woman Shrugging' },
      { emoji: '🤦', code: '&#129318;', description: 'Person Facepalming' },
      { emoji: '🤦‍♂️', code: '&#129318;&#9794;', description: 'Man Facepalming' },
      { emoji: '🤦‍♀️', code: '&#129318;&#9792;', description: 'Woman Facepalming' },
    ]
  },
  {
    groupName: 'Hand Emojis',
    characters: [
      { emoji: '👍', code: '&#128077;', description: 'Thumbs Up' },
      { emoji: '👎', code: '&#128078;', description: 'Thumbs Down' },
      { emoji: '👌', code: '&#128076;', description: 'OK Hand' },
      { emoji: '✌️', code: '&#9996;', description: 'Victory Hand' },
      { emoji: '👋', code: '&#128075;', description: 'Waving Hand' },
      { emoji: '👏', code: '&#128079;', description: 'Clapping Hands' },
      { emoji: '🙏', code: '&#128591;', description: 'Folded Hands' },
      { emoji: '🤲', code: '&#129330;', description: 'Palms Up Together' },
      { emoji: '🤝', code: '&#129309;', description: 'Handshake' },
      { emoji: '✋', code: '&#9995;', description: 'Raised Hand' },
      { emoji: '🖐️', code: '&#128400;', description: 'Hand with Fingers Splayed' },
      { emoji: '🤚', code: '&#129306;', description: 'Raised Back of Hand' },
      { emoji: '🖖', code: '&#128406;', description: 'Vulcan Salute' },
      { emoji: '👊', code: '&#128074;', description: 'Oncoming Fist' },
      { emoji: '🤛', code: '&#129307;', description: 'Left-Facing Fist' },
      { emoji: '🤜', code: '&#129308;', description: 'Right-Facing Fist' },
      { emoji: '🤞', code: '&#129310;', description: 'Crossed Fingers' },
      { emoji: '🤟', code: '&#129311;', description: 'Love-You Gesture' },
      { emoji: '🤘', code: '&#129304;', description: 'Sign of the Horns' },
      { emoji: '👌', code: '&#128076;', description: 'OK Hand' },
      { emoji: '✍️', code: '&#9997;', description: 'Writing Hand' },
      { emoji: '👈', code: '&#128072;', description: 'Backhand Index Pointing Left' },
      { emoji: '👉', code: '&#128073;', description: 'Backhand Index Pointing Right' },
      { emoji: '👆', code: '&#128070;', description: 'Backhand Index Pointing Up' },
      { emoji: '👇', code: '&#128071;', description: 'Backhand Index Pointing Down' },
      { emoji: '☝️', code: '&#9757;', description: 'Index Pointing Up' }
    ]
  },
  {
    groupName: 'Animals & Nature',
    characters: [
      { emoji: '🙈', code: '&#128584;', description: 'See-No-Evil Monkey' },
      { emoji: '🙉', code: '&#128585;', description: 'Hear-No-Evil Monkey' },
      { emoji: '🙊', code: '&#128586;', description: 'Speak-No-Evil Monkey' },
      { emoji: '🐒', code: '&#128018;', description: 'Monkey' },
      { emoji: '🐶', code: '&#128054;', description: 'Dog Face' },
      { emoji: '🐱', code: '&#128049;', description: 'Cat Face' },
      { emoji: '🐭', code: '&#128045;', description: 'Mouse Face' },
      { emoji: '🦁', code: '&#129409;', description: 'Lion Face' },
      { emoji: '🐮', code: '&#128046;', description: 'Cow Face' },
      { emoji: '🐷', code: '&#128055;', description: 'Pig Face' },
      { emoji: '🐸', code: '&#128056;', description: 'Frog Face' },
      { emoji: '🐼', code: '&#128060;', description: 'Panda Face' },
      { emoji: '🐧', code: '&#128039;', description: 'Penguin' },
      { emoji: '🐦', code: '&#128038;', description: 'Bird' },
      { emoji: '🦋', code: '&#129419;', description: 'Butterfly' },
      { emoji: '🌸', code: '&#127800;', description: 'Cherry Blossom' },
      { emoji: '🌻', code: '&#127803;', description: 'Sunflower' },
      { emoji: '🌲', code: '&#127794;', description: 'Evergreen Tree' },
      { emoji: '🌍', code: '&#127757;', description: 'Earth Globe Europe-Africa' },
    ]
  },
  {
    groupName: 'Food & Drink',
    characters: [
      { emoji: '🍏', code: '&#127823;', description: 'Green Apple' },
      { emoji: '🍎', code: '&#127822;', description: 'Red Apple' },
      { emoji: '🍉', code: '&#127817;', description: 'Watermelon' },
      { emoji: '🍌', code: '&#127820;', description: 'Banana' },
      { emoji: '🍓', code: '&#127827;', description: 'Strawberry' },
      { emoji: '🍒', code: '&#127826;', description: 'Cherries' },
      { emoji: '🍇', code: '&#127815;', description: 'Grapes' },
      { emoji: '🍔', code: '&#127828;', description: 'Hamburger' },
      { emoji: '🍕', code: '&#127829;', description: 'Pizza' },
      { emoji: '🌭', code: '&#127789;', description: 'Hot Dog' },
      { emoji: '🍣', code: '&#127843;', description: 'Sushi' },
      { emoji: '🍿', code: '&#127871;', description: 'Popcorn' },
      { emoji: '🍦', code: '&#127846;', description: 'Ice Cream' },
      { emoji: '🍩', code: '&#127849;', description: 'Doughnut' },
      { emoji: '☕', code: '&#9749;', description: 'Hot Beverage' },
    ]
  },
  {
    groupName: 'Travel & Places',
    characters: [
      { emoji: '🚗', code: '&#128663;', description: 'Car' },
      { emoji: '🚕', code: '&#128661;', description: 'Taxi' },
      { emoji: '🚙', code: '&#128665;', description: 'SUV' },
      { emoji: '🚌', code: '&#128652;', description: 'Bus' },
      { emoji: '🚓', code: '&#128660;', description: 'Police Car' },
      { emoji: '🚑', code: '&#128657;', description: 'Ambulance' },
      { emoji: '🚒', code: '&#128658;', description: 'Fire Engine' },
      { emoji: '✈️', code: '&#9992;', description: 'Airplane' },
      { emoji: '🚢', code: '&#128674;', description: 'Ship' },
      { emoji: '🗽', code: '&#127467;', description: 'Statue of Liberty' },
      { emoji: '🏰', code: '&#127984;', description: 'Castle' },
    ]
  },
  {
    groupName: 'Money Emojis',
    characters: [
      { emoji: '💵', code: '&#128181;', description: 'Dollar Banknote' },
      { emoji: '💴', code: '&#128180;', description: 'Yen Banknote' },
      { emoji: '💶', code: '&#128182;', description: 'Euro Banknote' },
      { emoji: '💷', code: '&#128183;', description: 'Pound Banknote' },
      { emoji: '💰', code: '&#128176;', description: 'Money Bag' },
      { emoji: '💳', code: '&#128179;', description: 'Credit Card' },
      { emoji: '💎', code: '&#128142;', description: 'Gem Stone' },
      { emoji: '💸', code: '&#128184;', description: 'Money with Wings' },
      { emoji: '💱', code: '&#128177;', description: 'Currency Exchange' },
      { emoji: '💲', code: '&#128178;', description: 'Heavy Dollar Sign' },
      { emoji: '🪙', code: '&#129689;', description: 'Coin' },
      { emoji: '🏦', code: '&#127974;', description: 'Bank' },
      { emoji: '🤑', code: '&#129297;', description: 'Money-Mouth Face' },
      { emoji: '🤲💰', code: '&#129330;&#128176;', description: 'Hands Receiving Money' }
    ]
  },
  {
    groupName: 'Objects & Symbols',
    characters: [
      { emoji: '📱', code: '&#128241;', description: 'Mobile Phone' },
      { emoji: '💻', code: '&#128187;', description: 'Laptop' },
      { emoji: '⌚', code: '&#8986;', description: 'Watch' },
      { emoji: '📷', code: '&#128247;', description: 'Camera' },
      { emoji: '🔑', code: '&#128273;', description: 'Key' },
      { emoji: '🔨', code: '&#128296;', description: 'Hammer' },
      { emoji: '💡', code: '&#128161;', description: 'Light Bulb' },
      { emoji: '⛱️', code: '&#9969;', description: 'Umbrella' },
      { emoji: '🎈', code: '&#127880;', description: 'Balloon' },
      { emoji: '🎁', code: '&#127873;', description: 'Wrapped Gift' },
      { emoji: '⏰', code: '&#9200;', description: 'Alarm Clock' },
      { emoji: '🧸', code: '&#129518;', description: 'Teddy Bear' },
      { emoji: '🔒', code: '&#128274;', description: 'Locked' },
      { emoji: '📏', code: '&#128207;', description: 'Ruler' },
      { emoji: '📌', code: '&#128204;', description: 'Pushpin' },
    ]
  },
  {
    groupName: 'Flags',
    characters: [
      { emoji: '🇺🇸', code: '&#127482;', description: 'Flag: United States' },
      { emoji: '🇬🇧', code: '&#127468;', description: 'Flag: United Kingdom' },
      { emoji: '🇨🇦', code: '&#127464;', description: 'Flag: Canada' },
      { emoji: '🇦🇺', code: '&#127462;', description: 'Flag: Australia' },
      { emoji: '🇫🇷', code: '&#127467;', description: 'Flag: France' },
      { emoji: '🇩🇪', code: '&#127465;', description: 'Flag: Germany' },
      { emoji: '🇮🇹', code: '&#127470;', description: 'Flag: Italy' },
      { emoji: '🇺🇦', code: '&#127482;&#127462;', description: 'Flag: Ukraine' },
      { emoji: '🇵🇱', code: '&#127477;', description: 'Flag: Poland' },
      { emoji: '🇯🇵', code: '&#127471;', description: 'Flag: Japan' },
      { emoji: '🇰🇷', code: '&#127472;', description: 'Flag: South Korea' },
      { emoji: '🇨🇳', code: '&#127464;', description: 'Flag: China' },
      { emoji: '🇧🇷', code: '&#127463;', description: 'Flag: Brazil' },
      { emoji: '🇮🇳', code: '&#127470;', description: 'Flag: India' },
      { emoji: '🇷🇺', code: '&#127479;', description: 'Flag: Russia' },
      { emoji: '🇲🇽', code: '&#127474;', description: 'Flag: Mexico' },
      { emoji: '🇿🇦', code: '&#127487;', description: 'Flag: South Africa' },
    ]
  }
];

export { emojiEntities };
